name = "GridOptimizationChallenge1"
uuid = "6aa5fae6-71f7-410b-bed7-6c0b2b07eeb8"
authors = ["Juan Luis Barberia <jbarberia@frba.utn.edu.ar> and contributors"]
version = "0.1.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
JuMP = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
